[project]
name = "uv-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate>=1.6.0",
    "click>=8.1.8",
    "einops>=0.8.1",
]
